{
    "name": "Boolean Button Widget",
    "version": "13.0.0.1.0",
    "category": "Web",
    "summary": "",
    "license": "LGPL-3",
    "author": "Odoo Community Association (OCA)," "Sergei Ruzki,",
    "website": "http://bigdata.by/",
    "depends": ["web"],
    "data": ["views/templates.xml"],
    "qweb": [],
    "installable": True,
    "application": False,
    "auto_install": False,
}
